'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { X, Printer, Download, Share2, Package, User, CreditCard, Calendar, ShieldCheck } from 'lucide-react';
import { useCurrency } from '@/components/CurrencyContext';
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function InvoiceModal({ sale, onClose }: { sale: any, onClose: () => void }) {
  const { formatPrice } = useCurrency();

  const downloadPDF = () => {
    const doc = new jsPDF();
    const primaryColor: [number, number, number] = [6, 182, 212]; // Cyan-500
    
    // Add Header
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('AURASALES', 14, 25);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('BUSINESS MANAGEMENT SUITE', 14, 32);
    
    doc.setFontSize(18);
    doc.text('INVOICE', 160, 25);
    doc.setFontSize(10);
    doc.text(sale.invoiceId || `#${sale._id.slice(-8).toUpperCase()}`, 160, 32);

    // Customer & Info Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('BILLED TO:', 14, 55);
    doc.setFont('helvetica', 'normal');
    doc.text(sale.customerId?.name || 'Guest Customer', 14, 62);
    doc.text(sale.customerId?.phone || 'No phone', 14, 67);
    doc.text(sale.customerId?.address || '', 14, 72);

    doc.setFont('helvetica', 'bold');
    doc.text('DETAILS:', 140, 55);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${format(new Date(sale.date), 'PPP')}`, 140, 62);
    doc.text(`Status: ${sale.status || 'PAID'}`, 140, 67);
    doc.text(`Payment: ${sale.paymentType}`, 140, 72);

    // Table
    const tableData = sale.items.map((item: any) => [
      item.name,
      item.quantity,
      formatPrice(item.unitPrice || (item.totalPrice / item.quantity)),
      formatPrice(item.totalPrice || (item.sellingPrice * item.quantity))
    ]);

    autoTable(doc, {
      startY: 85,
      head: [['Product', 'Qty', 'Unit Price', 'Total']],
      body: tableData,
      headStyles: { fillColor: primaryColor, textColor: 255 },
      styles: { fontSize: 9 },
      alternateRowStyles: { fillColor: [245, 247, 250] }
    });

    // Summary
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Subtotal:', 140, finalY);
    doc.text(formatPrice(sale.totalAmount), 180, finalY, { align: 'right' });
    
    doc.setFontSize(14);
    doc.setTextColor(...primaryColor as [number, number, number]);
    doc.text('Grand Total:', 140, finalY + 10);
    doc.text(formatPrice(sale.totalAmount), 180, finalY + 10, { align: 'right' });

    if (sale.dueAmount > 0) {
      doc.setTextColor(225, 29, 72); // rose-600
      doc.text('Amount Due:', 140, finalY + 20);
      doc.text(formatPrice(sale.dueAmount), 180, finalY + 20, { align: 'right' });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by AuraSales Business Suite', 105, 285, { align: 'center' });

    doc.save(`Invoice_${sale.invoiceId || sale._id.slice(-8)}.pdf`);
  };

  if (!sale) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
        className="absolute inset-0 bg-black/80 backdrop-blur-md"
      />
      <motion.div 
        initial={{ scale: 0.9, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.9, opacity: 0, y: 20 }}
        className="glass-panel w-full max-w-4xl max-h-[90vh] rounded-[2.5rem] relative z-10 shadow-2xl border border-white/10 overflow-hidden flex flex-col"
      >
        {/* Header */}
        <div className="p-6 md:p-10 flex items-center justify-between border-b border-white/5 bg-white/5">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-cyan-500 rounded-2xl flex items-center justify-center shadow-lg shadow-cyan-500/30">
              <ShieldCheck className="text-white" size={24} />
            </div>
            <div>
              <h2 className="text-2xl font-black tracking-tight">Invoice Details</h2>
              <p className="text-gray-400 font-mono text-xs uppercase tracking-widest">{sale.invoiceId || `#${sale._id.slice(-8).toUpperCase()}`}</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button className="p-3 bg-white/5 hover:bg-white/10 rounded-xl transition-all text-gray-400 hover:text-white" title="Print">
              <Printer size={20} />
            </button>
            <button 
              onClick={downloadPDF}
              className="p-3 bg-white/5 hover:bg-white/10 rounded-xl transition-all text-gray-400 hover:text-white" 
              title="Download PDF"
            >
              <Download size={20} />
            </button>
            <button onClick={onClose} className="p-3 bg-white/5 hover:bg-rose-500/20 rounded-xl transition-all text-gray-400 hover:text-rose-400 ml-2">
              <X size={20} />
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 md:p-10 space-y-10 scrollbar-hide">
          {/* Customer & Transaction Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-6">
              <div className="flex items-center gap-3 text-cyan-400 font-bold uppercase tracking-widest text-[10px]">
                <User size={14} />
                <span>Customer Information</span>
              </div>
              <div className="bg-white/5 p-6 rounded-3xl border border-white/5">
                <h3 className="text-xl font-bold">{sale.customerId?.name || 'Guest Customer'}</h3>
                <p className="text-gray-400 text-sm mt-1">{sale.customerId?.phone || 'No phone provided'}</p>
                <p className="text-gray-400 text-xs mt-0.5">{sale.customerId?.address || 'No address provided'}</p>
                
                {sale.customerId && (
                  <div className="mt-6 pt-6 border-t border-white/5 grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-[10px] text-gray-500 font-black uppercase tracking-tighter">Total Spent</p>
                      <p className="text-sm font-bold">{formatPrice(sale.customerId.totalSpent || 0)}</p>
                    </div>
                    <div>
                      <p className="text-[10px] text-gray-500 font-black uppercase tracking-tighter">Pending Due</p>
                      <p className="text-sm font-bold text-rose-400">{formatPrice((sale.customerId.totalSpent || 0) - (sale.customerId.totalPaid || 0))}</p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            <div className="space-y-6">
              <div className="flex items-center gap-3 text-indigo-400 font-bold uppercase tracking-widest text-[10px]">
                <Calendar size={14} />
                <span>Payment Details</span>
              </div>
              <div className="bg-white/5 p-6 rounded-3xl border border-white/5 space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-gray-400 text-sm font-medium">Date</span>
                  <span className="text-sm font-bold">{format(new Date(sale.date), 'PPP p')}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-gray-400 text-sm font-medium">Payment Method</span>
                  <span className="px-3 py-1 bg-cyan-500/10 text-cyan-400 text-[10px] font-black rounded-lg border border-cyan-500/20 uppercase">
                    {sale.paymentType}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-gray-400 text-sm font-medium">Status</span>
                  <span className={`px-3 py-1 text-[10px] font-black rounded-lg border uppercase ${
                    sale.status === 'PAID' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                    sale.status === 'PARTIAL' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' :
                    'bg-rose-500/10 text-rose-400 border-rose-500/20'
                  }`}>
                    {sale.status || 'PAID'}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Product Items */}
          <div className="space-y-6">
            <div className="flex items-center gap-3 text-emerald-400 font-bold uppercase tracking-widest text-[10px]">
              <Package size={14} />
              <span>Purchased Products</span>
            </div>
            <div className="glass-panel rounded-3xl overflow-hidden border border-white/5">
              <table className="w-full text-left">
                <thead>
                  <tr className="bg-white/5 text-[10px] font-black text-gray-400 uppercase tracking-widest">
                    <th className="p-4">Item Name</th>
                    <th className="p-4 text-center">Qty</th>
                    <th className="p-4 text-right">Unit Price</th>
                    <th className="p-4 text-right">Total</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {sale.items?.map((item: any, i: number) => (
                    <tr key={i} className="text-sm">
                      <td className="p-4">
                        <p className="font-bold">{item.name}</p>
                        <p className="text-[10px] text-gray-500">ID: {item.productId?._id || item.productId}</p>
                      </td>
                      <td className="p-4 text-center font-bold text-gray-300">{item.quantity}</td>
                      <td className="p-4 text-right font-medium">{formatPrice(item.unitPrice || (item.totalPrice / item.quantity))}</td>
                      <td className="p-4 text-right font-black text-cyan-400">{formatPrice(item.totalPrice || (item.sellingPrice * item.quantity))}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Summary */}
          <div className="flex flex-col items-end pt-10 border-t border-white/5 gap-4">
            <div className="w-full md:w-80 space-y-3">
              <div className="flex justify-between text-gray-400">
                <span className="text-sm font-medium">Subtotal</span>
                <span className="text-sm font-bold">{formatPrice(sale.totalAmount)}</span>
              </div>
              <div className="flex justify-between text-gray-400">
                <span className="text-sm font-medium">Discount</span>
                <span className="text-sm font-bold">{formatPrice(0)}</span>
              </div>
              <div className="flex justify-between items-center pt-3 border-t border-white/10">
                <span className="text-lg font-black text-white">Grand Total</span>
                <span className="text-3xl font-black text-cyan-400 tracking-tighter">{formatPrice(sale.totalAmount)}</span>
              </div>
              {sale.dueAmount > 0 && (
                <div className="flex justify-between items-center p-3 bg-rose-500/10 rounded-2xl border border-rose-500/20 mt-4">
                  <span className="text-xs font-bold text-rose-400 uppercase tracking-widest">Amount Due</span>
                  <span className="text-xl font-black text-rose-400">{formatPrice(sale.dueAmount)}</span>
                </div>
              )}
            </div>
          </div>

          {/* Notes */}
          {sale.notes && (
            <div className="p-6 bg-white/5 rounded-3xl border border-dashed border-white/10">
              <p className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-2">Notes</p>
              <p className="text-sm text-gray-300 italic">"{sale.notes}"</p>
            </div>
          )}
        </div>
        
        {/* Footer */}
        <div className="p-6 md:px-10 md:py-8 bg-white/5 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-gray-500 text-[10px] font-bold uppercase tracking-widest">
            <span>Handled by</span>
            <span className="text-white">Admin System</span>
          </div>
          <p className="text-gray-600 text-[10px] font-medium italic">Thank you for your business. For any queries, please contact support.</p>
        </div>
      </motion.div>
    </div>
  );
}
